### ISSUE TITLE
Make `mypy --strict` a gate, and make the standard say what is actually enforced

### ISSUE THREAD

**Issue by TBarregren** [Kntnt/kntnt-wp-skills#74]
> *This was generated by AI during triage.*

## Why this exists

Split from #71. That ticket reported two `mypy --strict` regressions and said in its own title that the real question was whether mypy should be a gate at all. It was right, and the question is now answered.

**Maintainer decision, 2026-08-21: a type error stops work from landing. A lint finding does not — yet.**

#71 keeps the two regressions, which have a verified repair and can land on their own. This ticket makes the gate real.

## What is true today, measured at `cec5113`

- No `pyproject.toml`, `mypy.ini`, `ruff.toml` or CI exists. `pytest.ini` is the only tool configuration in the repository.
- `CONTRIBUTING.md` names exactly one verification command: `uv run --with pytest pytest`. It never mentions a type checker or a linter.
- `agents.d/coding-standard/python.md` names ruff as the single linter and formatter, and mypy or pyright for static type checking with **"Strict mode on new code"** — a requirement nothing in the project enforces or can enforce.
- The helpers are standalone PEP 723 scripts. Every one declares `requires-python = ">=3.12"`. Exactly one, `skills/clone/scripts/unseal.py`, declares a dependency (`pynacl==1.5.0`); every other declares `dependencies = []`.

## How many errors there actually are, and why the number moves

The count depends on whether mypy can see the one declared dependency, and this matters more than it looks.

| Invocation | Errors | Files |
|---|---|---|
| `mypy --strict --ignore-missing-imports` | 8 | 5 |
| `mypy --strict` with `pynacl` provisioned | **7** | 4 |

The difference is a single `no-any-return` in the unseal helper, and it is **not a defect** — it is an artifact of `nacl.bindings` being invisible, so mypy cannot see that the value returned is already `bytes`. Provisioning the dependency makes it disappear. Blanket-ignoring missing imports manufactures it.

So the real backlog, with the dependency resolved, is **five** pre-existing errors beside #71's two:

| Module | Count | Error |
|---|---|---|
| `skills/clone/scripts/poll_extraction.py` | 4 | `union-attr` — attribute access on an `HttpResponse \| None` that is not narrowed first |
| `skills/clone/scripts/resolve_plan.py` | 1 | `no-any-return` — returning `Any` from a function declared `-> bool` |

**This corrects #71 twice.** It reported "eight further pre-existing errors… in `resolve_plan.py`, `unseal.py` and `poll_extraction.py`". Eight was the total including its own two, not a further eight; and once the dependency is provisioned the unseal entry is not real. The tree is seven errors from strict-clean, five of which this ticket owns — which is why gating is cheap enough to be worth doing now.

## What the absence of a gate has already cost

Thirty-two mentions of ruff or mypy across `plans/`, several carrying an explicit **"Never run `ruff check .`"** instruction to the executor, because a repo-wide run reports findings nobody configured and nobody owns. Every ticket in the recent queue has had to argue "pre-existing" in its own status row, and three independent verifiers ran mypy of their own accord, found the two real regressions, and correctly declined to fail a ticket on a check the project does not run.

## On ruff, and why it is not in this ticket

Ruff's finding count on this repository is **1 or 90 depending on the ruleset**, and the repository pins neither. A bare `uvx ruff check` reports 90. Ruff's documented stock default set, `E4,E7,E9,F`, reports exactly one — an unused `pytest` import in a test module. So "does this pass ruff?" has no answer here, and the 58–89 figure quoted in #71 is an artifact of an unpinned invocation rather than a property of the code.

Choosing that ruleset is a taste decision with a real spread behind it, and it is deferred deliberately. What this ticket owes ruff is honesty, not enforcement: the standard must stop implying a linter runs when none does.

## Blocked by

#71 — the two regressions must be clean before a gate can land green.

**Comment by TBarregren** [comment]
> *This was generated by AI during triage.*

## Agent Brief

**Category:** enhancement
**Summary:** Make strict type checking a verification step the project actually runs, clear the remaining type errors, and amend the Python standard so it states what is enforced rather than what is merely intended.

**Current behavior:**
The project's Python coding standard requires strict-mode static type checking on new code and names ruff as the single linter, but the repository carries no configuration for either and no CI, so neither ever runs. The only verification command the project documents is its test suite. Type regressions therefore land unnoticed — two did — and every executor re-derives from scratch which findings are pre-existing and whether a type or lint check is worth running at all, one status row at a time.

**Desired behavior:**
Strict type checking is a first-class verification step alongside the test suite: configured in the repository, documented as a command a contributor or an unattended agent runs, and passing cleanly across the whole helper tree. The Python standard states plainly what is enforced and what is only advised, so nobody has to re-derive it. No helper's runtime behaviour changes.

**Key interfaces:**

- **A repository-level type-checker configuration.** A `[tool.mypy]` section in a `pyproject.toml` is the conventional home. It must pin strict mode so that an invocation carrying no ad-hoc flags reproduces the gate. The helpers are standalone PEP 723 scripts, not a package — the configuration must not introduce a build backend, package metadata, or an installable distribution.
- **The dependency question, which is the one real design decision here.** Exactly one helper declares a third-party dependency; the rest declare none. When the type checker cannot see that dependency it invents an error that does not exist. **Resolve dependencies rather than suppressing missing imports** — a blanket ignore-missing-imports setting manufactures a phantom finding and weakens the check at the only boundary where a real one could hide. The documented command should provision the declared dependency the same way the scripts themselves do, through `uv`.
- **Each helper's PEP 723 header** — the `requires-python` floor and the `dependencies` list. Both must survive unchanged. No fix may add a runtime dependency, and none may require a Python newer than the declared floor.
- **`CONTRIBUTING.md`'s verification section** — today one command; it should name the type-check command beside it, in the same "one command, provisioned through `uv`" shape the test command already uses.
- **`agents.d/coding-standard/python.md`'s tooling lines** — they must end up describing the enforced state. Strict type checking is a gate. Ruff is the chosen linter but is unconfigured and advisory until a ruleset is pinned, so the result of a bare ruff run is not a verdict on a change and an executor should not treat it as one.
- **The remaining type errors, by shape rather than by location.** Four are attribute accesses on an optional HTTP-response value that is never narrowed before use. One is a function returning `Any` where a concrete `bool` is declared. Fix them by narrowing the optional and by making the returned value concrete. Do **not** widen a declared return type to `Any`, and do not silence anything with a suppression comment.

**Acceptance criteria:**

- [ ] Strict type checking over the whole helper tree reports zero errors, with no `type: ignore` comment introduced anywhere
- [ ] The gate reproduces from the repository's own configuration — the documented command relies on no ad-hoc command-line flags to reach that result
- [ ] The one declared third-party dependency is resolved during the check rather than ignored, and the phantom `no-any-return` its absence produces is gone because the dependency is visible, not because it was suppressed
- [ ] `uv run --with pytest pytest` passes at no fewer than the count on the commit this work is built from
- [ ] `CONTRIBUTING.md` names the type-check command alongside the test command
- [ ] `agents.d/coding-standard/python.md` no longer asserts an enforced linter: it states that strict type checking is enforced and that ruff is unconfigured and advisory pending a chosen ruleset
- [ ] Every helper still declares its original `requires-python` floor and its original `dependencies` list
- [ ] No helper's runtime behaviour changes — every fix is type-level only
- [ ] Any instruction in `plans/` telling an executor not to run a lint or type check is reconciled with the new state rather than left contradicting it
- [ ] The documentation round this repo charges every change of substance (rule R3) is paid

**Out of scope:**

- **The two regressions in #71.** This ticket is blocked by it and assumes they are already clean. Do not fix them here.
- **Choosing or configuring a ruff ruleset, and fixing any ruff finding.** The standard only has to stop implying ruff is enforced. The ruleset decision is deliberately deferred to the maintainer.
- **Adding CI.** This project has no CI and this ticket does not introduce it. The gate is a documented command, exactly as the test suite is.
- **pyright.** The standard offers mypy or pyright; mypy is what this codebase has been checked with and what stays.
- **The `bool`-versus-`int` boundary-helper question**, which is #70.
- Type-checking the test suite itself, which is not in the helper tree the standard's "strict on new code" rule was written for.

**Comment by TBarregren** [comment]
> *Written by an agent during a `ready-for-agent` readiness check, in a session that did not write the ticket. Nothing below changes the requirement: the corrections restate facts the repository no longer bears out, and anything named as a decision is left open for the maintainer.*

## Verdict: a builder could **not** carry this alone

Two things stop it. The first evaporates the moment #71 merges; the second does not, and needs a decision that is not a builder's to make.

## Stop 1 — the blocker is not cleared, and the ticket forbids the only route past it

> **Blocked by** — #71 — the two regressions must be clean before a gate can land green.
> **The two regressions in #71.** This ticket is blocked by it and assumes they are already clean. Do not fix them here.
> - [ ] Strict type checking over the whole helper tree reports zero errors

Measured at `cec5113`, both #71 regressions are still live:

```
skills/clone/scripts/smoke_test.py:782: error: Incompatible types in assignment ...  [assignment]
skills/clone/scripts/discovery.py:333: error: Argument 1 to "append" ... [arg-type]
```

#71 is **open**, with no branch and no PR (`main` is the only branch; the only PR ever opened, #72, is merged). So a builder dispatched today reaches the first acceptance criterion, finds two errors it is explicitly forbidden to touch, and has no instruction covering that state. It must ask: *has #71 landed somewhere I should build on, or may I fix these after all?*

**What would remove the stop:** name the branch or commit to build from ("build on the merge of #71"), plus the abort rule — *if `mypy --strict` still reports the `smoke_test.py` assignment or the `discovery.py` arg-type error, the blocker is unmet: stop and report it, do not fix them.* That converts an open question into a determinate abort.

## Stop 2 — the gate's file set is never named, and the ticket's survey of "the helpers" is false

> The helpers are standalone PEP 723 scripts. **Every one declares `requires-python = ">=3.12"`.** Exactly one, `skills/clone/scripts/unseal.py`, declares a dependency (`pynacl==1.5.0`); **every other declares `dependencies = []`**.
> - [ ] Strict type checking over **the whole helper tree** reports zero errors
> - [ ] Every helper still declares its original `requires-python` floor and its original `dependencies` list

There are 22 helper scripts. **Five of them are neither.** `skills/build-ollie-site/scripts/{check_contrast,dump_ground_truth,instantiate_patterns,lint_markup,mine_structures}.py` declare `requires-python = ">=3.10"` and carry **no `dependencies` key at all** — so the third criterion above is not merely inaccurate for them, it is unsatisfiable as written: they have no original `dependencies` list to preserve. `build-ollie-site` is one of the four skills this plugin ships, and `docs/spec.md:305` calls those files "Its own helpers".

The deliverable here is a config file whose `files = [...]` list **is** the scope decision, permanently. The two readings differ enormously:

| Scope | `mypy --strict` (pynacl provisioned) |
|---|---|
| `skills/clone/scripts` + `skills/mkwp/scripts` + `scripts` | **7 errors / 4 files** — exactly the ticket's table |
| + `skills/build-ollie-site/scripts` | **34 errors / 8 files** |

The extra 27 are not the shapes the ticket inventories: four `no-untyped-def`, nine `type-arg` on bare `dict`, and `mine_structures.py:303 Unsupported operand type for unary - ("object")`. Clearing them means adding TypedDicts or casts — work the ticket never scopes, and work that sits uncomfortably against "every fix is type-level only".

There **is** evidence for the narrow reading: `docs/spec.md:102` defines "the deterministic helper seam" as exactly those three homes, `docs/spec.md:305` says `build-ollie-site`'s helpers are *not* the transfer engine's helper seam, `pytest.ini`'s `pythonpath` is the same three, and the ticket's own counts reproduce on it precisely. A builder will probably land there. But it lands there by disbelieving the ticket's own universal claim about "the helpers", and it silently writes five shipped helpers out of the project's only enforced check — the kind of decision R3 says gets an ADR, taken unilaterally in an unwatched session.

**What would remove the stop:** one sentence naming the paths the config's `files` key must list, and one saying why `skills/build-ollie-site/scripts/` is or is not among them.

## Costs

**The reconciliation criterion's premise is off, and what actually contradicts the new state is elsewhere.**
> Any instruction in `plans/` telling an executor not to run a lint or type check is reconciled with the new state rather than left contradicting it.

There are **zero** mentions of mypy anywhere in `plans/` — all 33 ruff/mypy occurrences are ruff. And the ruff instructions do not contradict the new state: ruff stays unconfigured and advisory, so "Never run `ruff check .`" remains true. What *does* sit awkwardly is `plans/README.md:74`, which lists `uvx ruff check <the files you touched>` under "**Gates** — Every plan verifies against the repository's own gates", and the per-plan verification tables that make `ruff check → exit 0` a done criterion. Reconciling could mean doing nothing, editing one line, or rewriting nine plan files — most of them completed historical records with DONE status rows. All three defensible; none falsifiable. To be checkable it would have to name the file and say whether executed plans are archives or live instructions.

**R3 is not defined in this repository.** Its text lives at `~/Projects/kntnt-transfer-engine-open-work.md:83` — outside the repo, unreferenced by `AGENTS.md`, which mentions no documentation round at all. A builder can infer the shape from `plans/001-…md:433` ("Do all five: ADR, `docs/spec.md`, `CONTEXT.md`, `CHANGELOG.md`, both SKILL.md files"), but four of those five plainly do not apply to a tooling change with no runtime surface, so it must guess whether this warrants an ADR. If it writes one, `0029` is free — the highest on disk is `0028` and `main` is the only branch, so the ADR-collision hazard visible in recent commit subjects is not live. (#67, #71 and #75 charge the same undefined R3.)

**"Gate" collides with the project's binding glossary.** `CONTEXT.md:38` defines **Gate** as "A single yes/no prompt on a recommendation", and `docs/spec.md:3` makes the glossary binding "in code, documentation, and dialogue". The title and body use the word in the CI sense throughout. The acceptance criteria happen to say "enforced", which is the safe wording, but nothing flags the trap for the prose the builder writes into `CONTRIBUTING.md` and `python.md`.

**The type-check command is not given in runnable form, and "the same way the scripts themselves do" is not literally possible.**
> The documented command should provision the declared dependency the same way the scripts themselves do, through `uv`.

The scripts do it by PEP 723 header, which mypy cannot read. The builder must duplicate the `pynacl==1.5.0` pin into the command or the config — a second copy of a version the ticket separately requires to stay unchanged in `unseal.py`, with no word on which wins when they drift. Derivable in a minute (`uv run --with mypy --with pynacl==1.5.0 mypy`), but it is a decision, not a lookup.

**Nothing pins mypy.**
> The gate reproduces from the repository's own configuration

An unpinned `--with mypy` floats to whatever released last, so a future mypy can turn the gate red with no code change — recreating exactly the "argue it pre-existing in a status row" problem this ticket exists to end. `agents.d/coding-standard/python.md` says to pin exact versions; the existing `uv run --with pytest pytest` does not. Precedent and principle point opposite ways and the ticket does not choose.

**The count is 33, not thirty-two.** "Thirty-two mentions of ruff or mypy across `plans/`." Trivial, but a builder that verifies it pays a moment deciding whether the difference matters.

## What reproduces exactly, on the narrow tree

- `mypy --strict --ignore-missing-imports` over `skills/clone/scripts skills/mkwp/scripts scripts` → **8 errors in 5 files**.
- `uvx --with pynacl==1.5.0 mypy --strict` over the same → **7 errors in 4 files**, the `unseal.py:446 no-any-return` gone because `nacl.bindings` is visible rather than suppressed.
- The five this ticket owns: `poll_extraction.py:435,441,448,448` (four `union-attr` on `HttpResponse | None`) and `resolve_plan.py:525` (`no-any-return` on `-> bool`). Both fixes are straightforwardly type-level — a narrowing guard and a `bool(...)`.
- `uvx ruff check .` → **90**; `--select E4,E7,E9,F` → **1** (an unused `pytest` import).
- No `pyproject.toml`, `mypy.ini`, `ruff.toml` or `.github/`; `pytest.ini` is the only tool config. `CONTRIBUTING.md` names one verification command and never mentions a type checker or linter. `agents.d/coding-standard/python.md` is the only file to amend.
- Suite green at `cec5113`: **1257 passed**. The ticket wisely quotes no count.

Three mechanics the plan depends on and the ticket asserts none of, verified empirically:

- `strict = true` plus `files = [...]` in `[tool.mypy]` works with **zero** command-line flags on mypy 2.3.1 — so the "no ad-hoc flags" criterion is reachable.
- A `[tool.mypy]`-only `pyproject.toml` at the root does **not** break `uv run --with pytest pytest` (it creates `.venv/`, already gitignored) and does **not** break PEP 723 execution — `uv run dep.py` still resolves the inline `pynacl` dependency with a project file present.
- `pynacl` ships type information, so provisioning it produces no `import-untyped` error.

**Comment by TBarregren** [comment]
> *Correction and decision, from the same readiness check as the previous comment. The maintainer settled the scope question below on 2026-08-21.*

## Stop 1 is withdrawn — a blocked ticket is not a defective one

My previous comment reported the open #71 blocker as a stop. **It is not one.** "Blocked by: #71" is the abort rule, stated where it belongs, and a ticket is not dispatched while its blocker is open — #71 being open is simply what an open ticket is. Nothing in this ticket needs changing on that account, and the suggested "name the commit to build from, plus an abort rule" was redundant with the blocked-by declaration the ticket already carries.

This ticket has **one** stop, not two, and it is now settled below.

## Stop 2 settled — the gate covers the transfer engine's helper seam only

**Decision:** the config's `files` key lists exactly three paths, and no others:

```toml
[tool.mypy]
strict = true
files = ["scripts", "skills/clone/scripts", "skills/mkwp/scripts"]
```

`skills/build-ollie-site/scripts/` is **deliberately excluded**, and the exclusion is to be stated in the config itself rather than left as an omission a reader has to notice.

**Why.** The project already draws this line and this ticket should not redraw it: `docs/spec.md:102` defines "the deterministic helper seam" as exactly those three homes, and `docs/spec.md:305` says in as many words that `build-ollie-site`'s helpers are *not* the transfer engine's helper seam. `pytest.ini`'s `pythonpath` is the same three. The ticket's own error table reproduces precisely on this scope — **7 errors in 4 files** with `pynacl` provisioned — so every count in the ticket stands as written.

The alternative was measured rather than assumed: adding `skills/build-ollie-site/scripts/` gives **34 errors in 8 files**. The extra 27 are not the shapes this ticket inventories — four `no-untyped-def`, nine `type-arg` on bare `dict`, and `mine_structures.py:303 Unsupported operand type for unary - ("object")` — and clearing them means introducing TypedDicts or casts, which contradicts this ticket's own "every fix is type-level only". Those five files are also written against a different standard: `requires-python = ">=3.10"` and **no `dependencies` key at all**.

## Two consequences of that decision, both binding on this ticket

**1. The third acceptance criterion needs one word.** As written it is unsatisfiable for the excluded files:

> - [ ] Every helper still declares its original `requires-python` floor and its original `dependencies` list

The five `build-ollie-site` helpers have no `dependencies` list to preserve. Read the criterion as scoped to the helpers the gate covers — the 17 under the three listed paths, all of which do declare `requires-python = ">=3.12"` and `dependencies = []`, exactly as the body says. The body's "Every one" is true of the seam, not of all 22 scripts on disk.

**2. `build-ollie-site`'s helpers need their own ticket.** They are shipped code in one of the four skills this plugin distributes, and this decision leaves them outside the project's only enforced check. That is acceptable as a scope boundary and unacceptable as a silent one. A follow-up should widen the gate to them on their own terms — their own Python floor, their own error shapes — and it should be filed when this ticket lands, not folded into it.

## The costs from the previous comment still stand

Unchanged by this decision: the `plans/` reconciliation criterion (zero mypy mentions there — all 33 occurrences are ruff; what actually needs reconciling is `plans/README.md:74`'s Gates section), R3 being undefined in this repository, `CONTEXT.md:38`'s binding definition of **Gate** colliding with the CI sense used in the title and body, the type-check command needing the `pynacl==1.5.0` pin duplicated because mypy cannot read a PEP 723 header, mypy itself being unpinned, and the count being 33 rather than thirty-two.
